name: openapi_dart
description: Build Dart response models from Open Api (Swagger) documentation.
repository: https://github.com/herveGuigoz/openapi_dart
homepage: https://github.com/herveGuigoz/openapi_dart
version: 0.0.1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  meta: ^1.2.4
  collection: ^1.14.13
  riverpod: ^0.12.1
  freezed_annotation:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  build_runner:
  freezed:
